### ISSUE TITLE
无法部署war

### ISSUE THREAD

**Issue by l89669** [yushijinhun/authlib-agent#12]
尝试过多个平台，Centos，Ubuntu，Windows，全部都是一部署就报以下的错误
严重: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverIdRepositoryImpl' defined in file [C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\yggdrasil-backend\WEB-INF\classes\yushijinhun\authlibagent\dao\ServerIdRepositoryImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [yushijinhun.authlibagent.dao.ServerIdRepositoryImpl]: Constructor threw exception; nested exception is net.sf.ehcache.config.InvalidConfigurationException: There are 4 errors in your configuration: 
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly`
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1105)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1312)
	at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:690)
	at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:216)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:136)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [yushijinhun.authlibagent.dao.ServerIdRepositoryImpl]: Constructor threw exception; nested exception is net.sf.ehcache.config.InvalidConfigurationException: There are 4 errors in your configuration: 
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly

	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	... 47 more
Caused by: net.sf.ehcache.config.InvalidConfigurationException: There are 4 errors in your configuration: 
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly

	at net.sf.ehcache.config.Configuration.setupFor(Configuration.java:250)
	at net.sf.ehcache.CacheManager.doInit(CacheManager.java:436)
	at net.sf.ehcache.CacheManager.init(CacheManager.java:395)
	at net.sf.ehcache.CacheManager.<init>(CacheManager.java:270)
	at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:1116)
	at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:892)
	at net.sf.ehcache.CacheManager.create(CacheManager.java:873)
	at net.sf.ehcache.CacheManager.getInstance(CacheManager.java:907)
	at yushijinhun.authlibagent.dao.ServerIdRepositoryImpl.<init>(ServerIdRepositoryImpl.java:12)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 49 more

使用的tomcat7，mysql，redis均为软件源中的最新版本，机器内存高于8G
值得一提的是在applicationContext_redis中删除了redis的密码
也值得一提的是我曾经部署成功过（见#11），但是某个问题调试不好，直接重新clone，build，就一直出现此问题了
centos是多次部署，ubuntu和windows是首次部署就出现该问题

**Comment by yushijinhun** [comment]
你可以调低`BACKEND_CACHE_MAX_ON_HEAP`，或者调高tomcat最大内存

**Comment by l89669** [comment]
终于部署完成了，非常感谢您的协助
顺便想问一下，如果我想限制只有指定的ip上的服务器才能使用我部署的验证服务，如何设置Ip过滤呢？
我现在的配置是nginx+tomcat 部署在两台不同的机器上，nginx使用proxy_pass转发请求

**Comment by yushijinhun** [comment]
不太清楚你是什么意思，ip过滤可以用iptables实现。

**Comment by l89669** [comment]
意思是想问如何设置只有指定的ip上的minecraft服务端才能使用我部署的验证服务
还有一个问题
`[Tomcat access日志记录]
115.159.215.104 - - [04/May/2017:17:50:05 +0800] "GET /yggdrasil-backend/profiles/minecraft/c0cde676339c4a1d81edbd3bbe940fa7?unsigned=true HTTP/1.0" 404 47`
这里为什么会返回404，跟正版验证服务器有什么不同吗？

**Comment by l89669** [comment]
ps. 尝试中文角色名出错
Server log: 
`[23:13:09 ERROR]: Username '徘徊丶丶' tried to join with an invalid session

[23:13:09 INFO]: com.mojang.authlib.GameProfile@748f8946[id=<null>,name=徘徊丶丶,properties={},legacy=false] (/127.0.0.1:50456) lost connection: Failed to verify username!`

Tomcat access log
`115.159.215.104 - - [04/May/2017:23:13:09 +0800] "POST /yggdrasil-backend/yggdrasil/joinserver HTTP/1.0" 204 -
115.159.215.104 - - [04/May/2017:23:13:09 +0800] "GET /yggdrasil-backend/yggdrasil/hasjoinserver?serverId=148805018cd22a72ff95f6aef15975b790aed353&username=%E5%BE%98%E5%BE%8A%E4%B8%B6%E4%B8%B6 HTTP/1.0" 204 -`

**Comment by yushijinhun** [comment]
1. 有不同，api的endpoint你可以参考[这个](https://github.com/to2mbn/authlib-agent/blob/master/authlib-javaagent/config.properties)
2. 这个不是中文造成的问题，你应该检查一下
   1. 服务端和客户端是不是都已经加载了javaagent
   2. 启动器给mc传入的accesstoken是否有效

**Comment by yushijinhun** [comment]
ip访问控制你看一下这个：https://github.com/to2mbn/authlib-agent/wiki/Manager-API#mc%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6api ，不知道是不是你想要的。

**Comment by l89669** [comment]
再次感谢耐心帮助
中文的问题已经解决了，需要修改tomcat的配置
但是仍然会在登陆时报错
tomcat log: 
> 115.159.215.104 - - [04/May/2017:17:50:05 +0800] "GET /yggdrasil-backend/profiles/minecraft/c0cde676339c4a1d81edbd3bbe940fa7?unsigned=true HTTP/1.0" 404 47

client log: 
> Minecraft: com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
> Minecraft:      at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:75) ~[YggdrasilAuthenticationService.class:?]

对authlib验证本身没什么问题，只是报的404有点奇怪

**Comment by l89669** [comment]
已经解决了，原来是nginx配置错了目录。。。
