### ISSUE TITLE
无法加载正版用户的皮肤

### ISSUE THREAD

**Issue by nanpuyue** [yushijinhun/authlib-agent#20]
使用场景是这样的：

用yggdrasil-backend搭建了兼容正版登录的认证，然后正版用户使用原版客户端无法加载其他正版用户的皮肤，客户端报错如下：

```
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: java.security.SignatureException: Signature length not correct: got 256 but was expecting 512
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at java.security.Signature$Delegate.engineVerify(Signature.java:1219)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at java.security.Signature.verify(Signature.java:652)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at com.mojang.authlib.properties.Property.isSignatureValid(Property.java:47)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:134)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at cev$3.run(SourceFile:104)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:03:05] [pool-2-thread-1/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
[13:03:05] [pool-2-thread-1/ERROR]: Textures payload has been tampered with (signature invalid)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: java.security.SignatureException: Signature length not correct: got 256 but was expecting 512
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at java.security.Signature$Delegate.engineVerify(Signature.java:1219)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at java.security.Signature.verify(Signature.java:652)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at com.mojang.authlib.properties.Property.isSignatureValid(Property.java:47)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:134)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at cev$3.run(SourceFile:104)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:03:07] [pool-2-thread-1/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
[13:03:07] [pool-2-thread-1/ERROR]: Textures payload has been tampered with (signature invalid)
```

**Comment by nanpuyue** [comment]
提供以下链接以供参考：
https://mcauth.nanpuyue.com/profiles/minecraft/c17112cf3f0e44a0be2cf3fd0b5ccd6a
https://sessionserver.mojang.com/session/minecraft/profile/c17112cf3f0e44a0be2cf3fd0b5ccd6a

**Comment by nanpuyue** [comment]
看样子是签名的问题，请问有选项可以禁用签名么？

**Comment by yushijinhun** [comment]
是可以禁用的。

删除`yggdrasil-backend/src/main/resources`下的`signature_key.der`然后直接运行`mvn clean package`进行构建即可（构建输出在`yggdrasil-backend/target`下）。

这可能是一个bug，上面所述作为临时解决方法。我这个周末会看看能不能重现它。

**Comment by nanpuyue** [comment]
感谢回复。

仔细看了一下，从原理上讲必然会造成这样的情况，对于原版客户端，它会验证签名并且只认官方的私钥签出来的，而我们没有Mojang官方的私钥，如果对从官方获取到的角色信息进行重签名就必然导致原版客户端报错。

禁用签名的话，客户端也会包签名缺失，但是还没测试这样是否能够正常加载皮肤。

所以自己折腾了一下，注释了对正版用户的信息重签名的代码（同时在获取正版用户角色的URL中加上了unsigned=false），并替换了authlibagent.jar中的公钥为官方的。算是解决了正版用户皮肤不能加载的问题（服务器上主要是正版用户），但是非正版用户登录的话，正版用户客户端日志里还是会报签名错误。

**Comment by nanpuyue** [comment]
此外好像官方的签名是用的4096位的秘钥。

**Comment by yushijinhun** [comment]
这属于我当时设计这个功能时的失误。关于兼容正版的讨论在 #13 。当时我并没有考虑到正版用户显示textures的问题。

**Comment by nanpuyue** [comment]
酱紫，谢谢～
